### ISSUE TITLE
Manganato has been shut down

### ISSUE THREAD

**Issue by BenjaminPrice** [C9Glax/tranga#101]
Should probably remove it from the README at the very least, if not remove the entire connector.

**Comment by C9Glax** [comment]
Don't know what you mean
![image](https://github.com/C9Glax/tranga/assets/13404778/c119e8e2-4747-4d08-8f56-b0ff853ac9af)

**Comment by BenjaminPrice** [comment]
Perhaps GeoIP filtering then because this is what I see![image](https://github.com/C9Glax/tranga/assets/3983432/f6ee56c6-9e59-429e-9c32-eb8cf22df37f)
