### ISSUE TITLE
[It broke]: API-URI not working

### ISSUE THREAD

**Issue by ElryWeeb** [C9Glax/tranga#104]
### What is broken?

I installed the docker and have both routed to 127.0.0.1:port:port cuz im on a vps
but everytime i enter the api uri aka 127.0.0.1:6351 it just dissapears and does nothing.

**Comment by C9Glax** [comment]
Because you just pointed your Browser to ask at `127.0.0.1` which is your local computer. Unless you are hosting your docker instance on your computer that is not gonna work.

**Comment by ElryWeeb** [comment]
> Because you just pointed your Browser to ask at `127.0.0.1` which is your local computer. Unless you are hosting your docker instance on your computer that is not gonna work. Enter the IP of the machine tranga is running on

im connected to the tranga website trough an port tunnel, im actually accessing my vps, i will defenetly not open up the tranga api on my vps.

**Comment by ElryWeeb** [comment]
Maybe you have a solution how to fix that, installing a ui and accessing the ui inside the docker maybe ?

**Comment by C9Glax** [comment]
Well the webpage is only executing local javascript. There is no connection between the containers. So anything that is on the webpage is on your local machine. The webpage requests data from the api over http, so unless your local machine has access to tranga-api nothing is gonna happen.
Virtual desktop should work and then the IP would be 127.0.0.1.
