### ISSUE TITLE
Strip trailing whitespace from filenames (and more)

### ISSUE THREAD

**Issue by Volkor3-16** [C9Glax/tranga#113]
### What is broken?

It's not /really/ a proper bug, but it irks me a bit to see trailing whitespaces.

`'To You, The Immortal - Ch.54 .cbz'`

Half of the files from this manga have it.
I'd check others but I haven't started downloading any others yet.

I'm using the manganato connector for this one.

### Additional stuff

And because i'm too lazy to make another issue, is it possible to:
- Show the number of chapters in a manga selection before adding
- 'unmonitor' individual chapters, as I'll replace my more loved manga's with the full volume release from the publisher as I ~~pirate~~ buy them
- see/change the interval to check for new chapters
- open a direct link to the manga source
-  make the `/Jobs/Waiting` smaller? It seems like it's sending 3.8MB of text every second, which is hell on my data usage when accessing remotely. Is there a need to sync the full metadata of all manga jobs every second, instead of on demand?

Love your work, thanks for making actually usable software unlike the alternatives ❤️

**Comment by Volkor3-16** [comment]
> > Show the number of chapters in a manga selection before adding
> 
> You mean how many chapters there are in total?
> 
 
Yup :)

> > 'unmonitor' individual chapters, as I'll replace my more loved manga's with the full volume release from the publisher as I pirate buy them
> 
> hmm. Right now this would work somewhat with the checks if chapters exist. The Regex to check if a Chapter is already downloaded (so it isnt downloaded again) is `.*Vol(?:ume)?\.?([0-9]+).*Ch(?:apter)?\.?([0-9]+[\.0-9]*).*`. You can check for example [here](https://regexr.com/) if that would detect your chapters. I don't think I will implement this as a specific feature however...
> 

I didn't explain very well, the volumes are bundles of chapters in Tankōbon format with multiple chapters to a volume (Volume 1 being chapters 1-6). Ideally I could split it up, but doing this over my entire collection makes me want to cry.

I was thinking of a metadata tracking thing like sonarr, but that's wayy overkill (and where do you even get the metadata from?) It's much more simple to just track the chapters from the chosen source, and track monitored status, refusing to download any unmonitored.

In my head I'm picturing a split view (similar to the download queue view) that shows the description of the manga on the left, and a list of all the chapters, along with all their info on the right. - see awful 'design' attached lol

![image](https://github.com/C9Glax/tranga/assets/4054374/b9db37f8-271c-4984-a8dc-bcf3e3c755e0)

> > open a direct link to the manga source
> 
> Like a link on the tranga-interface that opens the manga on the original site?
> 

Yup :)

**Comment by C9Glax** [comment]
> and where do you even get the metadata from?

afaik there is no good central source for this type of stuff, so yea exactly.

I think what I am gonna do is: 
Select Chapters you want on first download and the option "automatically monitor new chapters".

**Comment by db-2001** [comment]
> > > Show the number of chapters in a manga selection before adding
> > 
> > 
> > You mean how many chapters there are in total?
> 
> Yup :)
> 
> > > 'unmonitor' individual chapters, as I'll replace my more loved manga's with the full volume release from the publisher as I pirate buy them
> > 
> > 
> > hmm. Right now this would work somewhat with the checks if chapters exist. The Regex to check if a Chapter is already downloaded (so it isnt downloaded again) is `.*Vol(?:ume)?\.?([0-9]+).*Ch(?:apter)?\.?([0-9]+[\.0-9]*).*`. You can check for example [here](https://regexr.com/) if that would detect your chapters. I don't think I will implement this as a specific feature however...
> 
> I didn't explain very well, the volumes are bundles of chapters in Tankōbon format with multiple chapters to a volume (Volume 1 being chapters 1-6). Ideally I could split it up, but doing this over my entire collection makes me want to cry.
> 
> I was thinking of a metadata tracking thing like sonarr, but that's wayy overkill (and where do you even get the metadata from?) It's much more simple to just track the chapters from the chosen source, and track monitored status, refusing to download any unmonitored.
> 
> In my head I'm picturing a split view (similar to the download queue view) that shows the description of the manga on the left, and a list of all the chapters, along with all their info on the right. - see awful 'design' attached lol
> 
> ![image](https://private-user-images.githubusercontent.com/4054374/303149511-b9db37f8-271c-4984-a8dc-bcf3e3c755e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODQ0NDEsIm5iZiI6MTcwNzQ4NDE0MSwicGF0aCI6Ii80MDU0Mzc0LzMwMzE0OTUxMS1iOWRiMzdmOC0yNzFjLTQ5ODQtYThkYy1iY2YzZTNjNzU1ZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMTMwOTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBiOGVmODAyOWQ0YTdhYmNmZWZjNDY3YzEwZDc5OWUxZjgyYWVmZmY2NDA5OTY4NTRhNjU0YTI0YTFmMjhiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r0dvdsUfo2oUnoWY_Ob_3Lrq9d9VLkH4wDB60eWdQBE)
> 
> > > open a direct link to the manga source
> > 
> > 
> > Like a link on the tranga-interface that opens the manga on the original site?
> 
> Yup :)

I plan to implement something exactly like this on the website side with a manga popup rework, so I kindly ask for your patience :)
