### ISSUE TITLE
[It broke]:  MangaWorld - can't add some Manga or Url 

### ISSUE THREAD

**Issue by bubez81** [C9Glax/tranga#115]
### What is broken?

as written here #103  for some manga the manual url insertion or the search doesn't work

two examples are:
https://www.mangaworld.ac/manga/2584/solo-max-level-newbie/
and:
https://www.mangaworld.ac/manga/2905/damn-reincarnation/

**Comment by C9Glax** [comment]
I moved back to the old issue for better documentation, don't know why I had closed that.
