### ISSUE TITLE
[Enchancement]: Left padding chapter and volumes numbers with lead 0 as an option

### ISSUE THREAD

**Issue by Charles-Em** [C9Glax/tranga#117]
### What is broken?

Hello,

Proposed enhancement is separated into two parts.

**Part 1 :**
I don't know how possible it would be to have an option (on a manga basis) to left pad volumes and chatpers with leading 0 (you set the number you want)
I know that ucrrently it would be with the rework you have mentionned.
Question is more about feasibility in the future.

**Part 2 :**
But currently, maybe the part where you scan current existing chapters could implement it?

For exemple if I rename "Tower of God - Vol.1 Ch.3 .cbz" to "Tower of God - Vol.1 Ch.003 .cbz" it would match it as existing in order to not redownload it.

My underlying issue is for webtoons (again lol), because tachiyomi reader (rip) propose different orderings that don't match my source :
- source order (kavita source, not working, it does rank all volumes chapters 1 then all volumes chapters 2, etc)
- chapter order (doesn't take volume into account, same problem as source)
- addition order (with some chapters here and there being failed and having to be redownloaded, this can't work)
- alphabetical order => I aim for this one, but it uses the first number encountered (purely alphabetical), so chapter 115 is before chapter 2, but chapter 002 would be before 115

I will look for the github of the replacement of tachiyomi to see if they can add a sort by volume/chapter (currently not existing) in the future.

Cheers

**Comment by db-2001** [comment]
Related to #92

**Comment by C9Glax** [comment]
Since this is basically #92 and now linked there, marking as duplicate and closing
