### ISSUE TITLE
Import current library

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga#120]
I’m moving over from Kaizoku and it would be nice if since they are both pointed to the same folder, Tranga would be able to see the current manga and add it automatically.

**Comment by C9Glax** [comment]
If you are thinking about completely automatic, not happening. At least not right now.
I have no clue what site you were using to download, the naming schema you would have been using, anything.

If you were thinking of something else, lmk.

**Comment by yacob841** [comment]
Should have done my research, I figured it would be included in the series.json but I just looked and it’s not. Thank you though.

**Comment by C9Glax** [comment]
Yea, dw. It's just not something that I have time for right now at all 😄

**Comment by yacob841** [comment]
I did think of something. You could potentially read the folders, read the json to get the ID, show them on the dashboard but somehow identify them as incomplete and you would need to edit it to pick what site to use. But what you said made sense

**Comment by moistdio** [comment]
@C9Glax Maybe a option for already existing files you already have? I agree you cant do that automatically, but you can give manually information.

**Comment by C9Glax** [comment]
@moistdio https://github.com/C9Glax/tranga/issues/222 this. future. faaar future.
