### ISSUE TITLE
[It broke]: Kavita Update

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga#121]
### What is broken?

Can not update Kavita settings

### Additional stuff

https://github.com/C9Glax/tranga-website/pull/41

**Comment by C9Glax** [comment]
@db-2001 can not reproduce...

**Comment by C9Glax** [comment]
![image](https://github.com/C9Glax/tranga/assets/13404778/56f9427e-bba3-4788-8f57-c665857f5c74)
![image](https://github.com/C9Glax/tranga/assets/13404778/b49361f9-5297-42e4-942d-3fc97ac9cc86)

**Comment by db-2001** [comment]
Hm, idk, I'll try it again with this new version and see what I'm doing wrong

**Comment by db-2001** [comment]
I get the Creating libraryConnector Kavita, but nothing happens after that. Is it possible to make a small PR to increase the logging to try and troubleshoot this on my end? Kavita doesn't need to be configured any special way right?

**Comment by C9Glax** [comment]
It should already have more logging by now.
https://github.com/C9Glax/tranga/blob/2872eeea0902380b57c3262d9c5a223050474cdb/Tranga/LibraryConnectors/Kavita.cs#L44

What I have noticed though is that sometimes Exceptions do not get logged.
And the thing that stands out to me the most rn is this
https://github.com/C9Glax/tranga/blob/2872eeea0902380b57c3262d9c5a223050474cdb/Tranga/LibraryConnectors/LibraryConnector.cs#L24
So if the uri does not match
https://github.com/C9Glax/tranga/blob/2872eeea0902380b57c3262d9c5a223050474cdb/Tranga/GlobalBase.cs#L19
Then it should throw an exception.

Maybe you can start a debug session on your machine and click through the steps? Good breakpoint would be the ["Creating libraryConnector Kavita"](https://github.com/C9Glax/tranga/blob/2872eeea0902380b57c3262d9c5a223050474cdb/Tranga/LibraryConnectors/LibraryConnector.cs#L23) line

**Comment by db-2001** [comment]
Alright, I'll try debugging on my end over the weekend 👍

**Comment by db-2001** [comment]
It's hashtags. 

My password for Kavita has a hashtag in it that I can see gets sent in the POST request but when I log this: 
![image](https://github.com/C9Glax/tranga/assets/125827669/579fc15b-d004-4835-a85d-071805dd782f)
The hashtag and anything following it is gone from the password. Don't know if this is the only issue but it's certainly one. It would explain why auth="" and we don't get past the `Creating libraryConector Kavita message`

Here's what I'm observing:

The HTTP Request
![image](https://github.com/C9Glax/tranga/assets/125827669/66340282-51e3-4a9b-a151-d14e9943b2db)

What the API gets: 
![image](https://github.com/C9Glax/tranga/assets/125827669/bdec5dd9-e40f-4458-acc2-de6f622df200)
Notice how "#word" is gone from the password. 

If the username has a `#` it returns a BadRequest immediately, which is probably fine in itself.

**Comment by C9Glax** [comment]
Yea `#` in uri's are treated like a seperator.
I think this should also be another push towards a json-API instead of a URI-based one...

**Comment by db-2001** [comment]
How big of a re-architecture would that be? Don't want to keep adding features to the old api and then have to rewrite them later

**Comment by C9Glax** [comment]
Basically the same data just on a json format, pushed as content, instead of withing the request.
The API already sends the data is json format, it's just the requests are being made "wrong".

**Comment by db-2001** [comment]
Ah, okay, read up on it a bit. Not a big change, I'll probably make a branch for that first before moving into other things.

**Comment by db-2001** [comment]
Is the API configured to receive JSON in a POST request? Doesn't seem to be working in my testing

**Comment by C9Glax** [comment]
No I phrased that wrong. The API is still only URI based, I need to rewrite so that it does json.

**Comment by db-2001** [comment]
Ah, okay, gotcha
