### ISSUE TITLE
[New Connector]: sushiscan.fr

### ISSUE THREAD

**Issue by maxouxx** [C9Glax/tranga#129]
### Website-Link

https://sushiscan.fr/

### Is the Website free to access?

- [X] The Website is freely accessible.

**Comment by C9Glax** [comment]
![Image](https://github.com/C9Glax/tranga/assets/13404778/02944f96-8444-426a-bab6-3f39803dbeff)

Is this a GeoBlocked site?

**Comment by maxouxx** [comment]
This site is mainly for french people. I used a VPN to access it from Poland and i got the same message as you. Is it a red flag ?

**Comment by db-2001** [comment]
I'm able to access the site from the US?

**Comment by C9Glax** [comment]
I can't access the site from Germany, the Netherlands, Japan... So I won't add it.
