### ISSUE TITLE
MangaSee search returns too many results - Fuzzysearch

### ISSUE THREAD

**Issue by ghost** [C9Glax/tranga#132]
### What is broken?

It just doesnt find anything in time, like im just staring at that screen for 3-5 minutes.

![image-2](https://github.com/C9Glax/tranga/assets/144011449/f0ad6165-48cf-457b-ace9-d50ee0793b4f)

FYI: MangaSee offers higher quality scans and also allows very high download speeds without throttling, thats why im using it.

FMD2 and Kaizuko both find search results for MangaSee in 1-2 seconds for One Piece that Tranga struggled with for minutes....

Idk why, but youre also getting wayyyy too many results for MangaSee searches...

Like One Piece returns 166 results while Kaizuko and FMD2 both only give about 4-5 results.

### Log-output

```C#
[02/27/2024 12:11:03.204] ChromiumDownl | Starting Browser.
[02/27/2024 12:11:04.164] ChromiumDownl | Starting Browser.
[02/27/2024 12:11:04.407]       JobBoss | Next job in
[02/27/2024 12:11:04.504]        Server | Listening on http://*:6531/
[02/27/2024 12:15:49.9  ]      Mangasee | Searching Publications. Term="One Piece"
[02/27/2024 12:15:52.632] ChromiumDownl | Page loaded.
[02/27/2024 12:15:52.864]      Mangasee | Total available manga: 7950 Filtered down to: 166
[02/27/2024 12:15:55.248] ChromiumDownl | Page loaded.
[02/27/2024 12:15:57.345] ChromiumDownl | Page loaded.
[02/27/2024 12:15:57.351]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/638446329552963622.jpg
[02/27/2024 12:15:59.376] ChromiumDownl | Page loaded.
[02/27/2024 12:16:01.456] ChromiumDownl | Page loaded.
[02/27/2024 12:16:01.500]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/638446329593889540.jpg

Repeat for 100 times...

[02/27/2024 12:26:50.547] ChromiumDownl | Page loaded.
[02/27/2024 12:26:52.595] ChromiumDownl | Page loaded.
[02/27/2024 12:26:52.599]      Mangasee | Saving cover to /usr/share/tranga-api/imageCache/638446336105760082.jpg
[02/27/2024 12:26:52.608]      Mangasee | Retrieved 166 publications. Term="One Piece"
```

**Comment by C9Glax** [comment]
https://github.com/C9Glax/tranga/issues/75

Read up on this. The Mangasee search itself is iffy, so I implemented my own, which sadly right now returns a lot of fake results. This is turn makes the search take ages, because tranga downloads all covers. 

Will repurpose this issue to improve the search for Mangasee.

**Comment by ElryWeeb** [comment]
> #75
> 
> Read up on this. The Mangasee search itself is iffy, so I implemented my own, which sadly right now returns a lot of fake results. This is turn makes the search take ages, because tranga downloads all covers.
> 
> Will repurpose this issue to improve the search for Mangasee.

Sorry but this is plain wrong, mangasee is one of the easier sources to scrape...

Litterally just use https://mangasee123.com/search/?sort=s&desc=false&name=

and then follow by the name entered in the text field replacing space with %20

Example for Made in Abyss:
![image](https://github.com/C9Glax/tranga/assets/144011449/c352bea5-ef7f-4967-b93b-758088681040)

The Results:
![image](https://github.com/C9Glax/tranga/assets/144011449/16e2793b-95cf-41a4-8178-9809c5c3149f)

**Comment by ElryWeeb** [comment]
I just noticed youre using C#, i will clone the repo and have a look myself if i can fix it.

**Comment by C9Glax** [comment]
> Sorry but this is plain wrong

![image](https://github.com/C9Glax/tranga/assets/13404778/f2ee4dc1-20e4-472f-818c-a6a492ed5bed)

right.

**Comment by C9Glax** [comment]
I am not stupid. Why would I go through the effort of writing my own stupid filter if I could use the site, like with every other connector.

**Comment by ElryWeeb** [comment]
> I just noticed youre using C#, i will clone the repo and have a look myself if i can fix it.

Thats not a problem for you to fix tho, thats a general issue with MangaSee.
People using MangaSee know how to move around these hurldles by using Romanji or using just a few words of the title.

**Comment by ElryWeeb** [comment]
Like i see 0 benefit if your search returns 166 Results for OP and takes 5 minutes while using the default search would take 5 seconds and give back 3 Results

**Comment by C9Glax** [comment]
Because the default way of doing it doesn't work!
Saying "it is plain wrong", when the search is indeed fucking broken, and you have to 

> move around these hurldles by using Romanji or using just a few words of the title

is not correct.

**Comment by ElryWeeb** [comment]
> Because the default way of doing it doesn't work! Saying "it is plain wrong", when the search is indeed fucking broken, and you have to
> 
> > move around these hurldles by using Romanji or using just a few words of the title
> 
> is not correct.

It does work and thats how i and others have been using it in FMD2 for years.

**Comment by ElryWeeb** [comment]
Its better to move around the Scrapers Search hurdles, especially if your own implementation is actually working even less.

**Comment by ElryWeeb** [comment]
Again im not trying to be mean here, but thats how it is at the moment.

**Comment by ElryWeeb** [comment]
If youre not willing to fix this for some reason, then im just going to do it myself and make a fork with it fixed

**Comment by C9Glax** [comment]
Yes it works. But not correctly. My search works, in that it returns ALL feasible (meaning all matches) for a string. Returning nothing because you are missing an apostrophe is in my book "not working". 

Yes it returns too many results, and the best way around that would be a fuzzy search, to which I just not have gotten.
The best way right now to add Mangasee manga is to use a direct link to the manga.

**Comment by ElryWeeb** [comment]
> Because the default way of doing it doesn't work! Saying "it is plain wrong", when the search is indeed fucking broken, and you have to
> 
> > move around these hurldles by using Romanji or using just a few words of the title
> 
> is not correct.


> Yes it works. But not correctly. My search works, in that it returns ALL feasible (meaning all matches) for a string. Returning nothing because you are missing an apostrophe is in my book "not working".
> 
> Yes it returns too many results, and the best way around that would be a fuzzy search, to which I just not have gotten. The best way right now to add Mangasee manga is to use a direct link to the manga.


Sorry but its lowkey out of scope to fix MangaSees broken search, that should be the job of the admins of mangasee.
But the users dont really care cuz its working "well enough", including me.
Why not revert it to the original Search and put this on a testing branch till it works like you want it to ?

**Comment by ElryWeeb** [comment]
> If youre not willing to fix this for some reason, then im just going to do it myself and make a fork with it fixed

Again just tell me and i will create a fork called TrangaSee for the time beeing, till you fixed the search.

**Comment by C9Glax** [comment]
Because people have been complaining that certain Manga just don't come up in results.
Of course it is up to Mangasee admins to fix their search, and if you want to use their search function you can do that!
You can add Manga to Tranga by using the URL of the Manga.

You are free to create your own fork, there is a commit somewhere that had the original search, you can just revert that and it should do the job.

**Comment by ElryWeeb** [comment]
> You can add Manga to Tranga by using the URL of the Manga.

Dont quite get how ? just paste the url in the searchbar ?

**Comment by ElryWeeb** [comment]
or only with the api directly ?

**Comment by ElryWeeb** [comment]
Also if i came over negative or mean, thats not what i wanted.
Im not really good with communicating and such stuff :(

**Comment by C9Glax** [comment]
Like this
![image](https://github.com/C9Glax/tranga/assets/13404778/c9b65ace-78fa-4e90-b3df-35edde9e7a7f)
So with the connector selected

**Comment by ElryWeeb** [comment]
Thank you so much, then i will use this :D

**Comment by ElryWeeb** [comment]
Oops you wanted to keep this open to track this.

**Comment by C9Glax** [comment]
Yup, thanks 👍🏼

**Comment by db-2001** [comment]
> > Sorry but this is plain wrong
> 
> ![image](https://private-user-images.githubusercontent.com/13404778/308353425-f2ee4dc1-20e4-472f-818c-a6a492ed5bed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMTg5MjUsIm5iZiI6MTcwOTExODYyNSwicGF0aCI6Ii8xMzQwNDc3OC8zMDgzNTM0MjUtZjJlZTRkYzEtMjBlNC00NzJmLTgxOGMtYTZhNDkyZWQ1YmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDExMTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxYWEzMDgwZDhjNTkwOGQ1YTNjNjQ3ZGQ3YTU2MWI1MzZmM2VlZjJmM2JjNjc0OTRiNmQ1NTRlMmU4YWZhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kT4A-J6T--Dbpb_eTHkYLIqaRAca0Au-rXJPd1gSS78)
> 
> right.

Noticing URL has "+" instead of "%20" for spaces, not sure if this makes a difference, just brining it up.

**Comment by C9Glax** [comment]
Nope, doesn't change a thing.

**Comment by C9Glax** [comment]
This should be fixed now.
