### ISSUE TITLE
[It broke]: Extremly slow Downloads

### ISSUE THREAD

**Issue by ElryWeeb** [C9Glax/tranga#136]
### What is broken?

The Downloads are extremly slow. 
Even with the new ui and setting the downloads per minute to 120.
It takes like up to a minute to download one chapter from MangaSee, even tho i can download like 2-3 chapters simularly which each taking 5 seconds in FMD2 without getting throttled by MangaSee.

### Additional stuff

I know you dont want this to like hit the servers of the scrapers too much, but FMD2 does the same and so far most of these have only IP banned and not the useragent of fmd and thats kinda the persons problem if they set their scraping too high.

As an Suggestion, the new UI already lets you set the max DL per Task, but currently thats not really doing anything. Its still slow.

**Comment by C9Glax** [comment]
you also need to change the useragent.
https://useragents.io/random
https://user-agent-generator-220418.netlify.app/#/

Otherwise it will use the default limits.

**Comment by ElryWeeb** [comment]
> you also need to change the useragent. https://useragents.io/random https://user-agent-generator-220418.netlify.app/#/
> 
> Otherwise it will use the default limits.

Where do i put the useragent string ?

**Comment by ElryWeeb** [comment]
Im a bit blind

**Comment by C9Glax** [comment]
![image](https://github.com/C9Glax/tranga/assets/13404778/b308bae3-49bd-498b-b751-275a8b3df22e)
Hope there are enough arrows 😛

**Comment by ElryWeeb** [comment]
Yes hahah, thank you so much.
