### ISSUE TITLE
[It broke]: Download Logs button no longer works.

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#139]
### What is broken?

The Download Logs button was working with the tranga branch we were testing with and then got merged into the main one. I'm not sure if something has been changed since then but now the logs are empty. Website code hasn't changed.

**Comment by C9Glax** [comment]
Can you check what the StatusCode is when you press the button?
![image](https://github.com/C9Glax/tranga/assets/13404778/214df7ee-37bd-4a14-812e-42493a805d0b)
Should either be a 404 or a 200

**Comment by db-2001** [comment]
Yeah returning 404 for me, I can see from your screenshot that you have a 200. I can see my logs in Portainer so the logger is enabled. Just don't know why it's returning a 404

**Comment by db-2001** [comment]
Hm, took down my tranga stack and redeployed it from the command line and it worked. I think this may have something to do with if you start/restart tranga from portainer or another container manager, it doesn't start the file logging?
