### ISSUE TITLE
tmp folder size

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga#142]
### What is broken?

I discovered this when I noticed that the size of this containers is almost 100x larger than most containers. It appears that the /tmp folder doesn't get properly managed and will keep increasing. I have 20 manga in my library (all fully downloaded) and my /tmp folder is 10GB

**Comment by C9Glax** [comment]
On linux `/tmp` gets automatically cleaned when it is mounted (e.g. on restart).
I added (for windows) a check that should cleanup all folders and files for tranga. How well this works on linux I don't know.
Folders should now be prefixed with "trangatemp".

**Comment by C9Glax** [comment]
Closing, if it's still too big, mention me.
