### ISSUE TITLE
Image Cache Duplicated

### ISSUE THREAD

**Issue by yacob841** [C9Glax/tranga#143]
### What is broken?

When attempting to figure out an issue with a large docker container I noticed there are duplicate image cache images. I have 20 manga currently in the library and I have 201 images in the image cache.

**Comment by C9Glax** [comment]
Image-Cache should clear once container is restarted. Can you restart and check if the cache is appropriately sized @yacob841

**Comment by C9Glax** [comment]
@yacob841 Need your input.

**Comment by yacob841** [comment]
Sorry, I’m pretty sure it was not clearing after container restart since mine restarts daily and it had dozens of each image. It’s been awhile since I’ve checked so I will try to double check this.

**Comment by C9Glax** [comment]
Ok should be clearing properly now.
