### ISSUE TITLE
[It broke]: 

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#166]
### What is broken?

Error trying to run latest cuttingedge branch locally: 

![image](https://github.com/C9Glax/tranga/assets/125827669/0779a5b1-91ff-47fd-9528-a5c6bee8bc3b)

This error is in the MangaDex.cs file

**Comment by C9Glax** [comment]
how is that value not there?!
https://api.mangadex.org/docs/03-manga/covers/#main-cover

> That relationship is always there and unique.

It found the `cover_art` relationship, so it should be there?

And I can't even reproduce with the [Manga you used](https://api.mangadex.org/manga/b05918e4-fb1a-4b10-a919-eaecf00fd7dd?includes%5B%5D=cover_art)

**Comment by C9Glax** [comment]
Found the issue...
