### ISSUE TITLE
[It broke]: Author and Genre Tags from Manganato contain /r/n elements

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#170]
### What is broken?

While working on V2 for the front end, I noticed that the author list and genre list from MangaNato has some extra /r/n elements which breaks the front end. Should be a simple Regex fix.

### Additional stuff

![image](https://github.com/C9Glax/tranga/assets/125827669/d81057de-edae-4c30-8093-38416adfec2f)

**Comment by C9Glax** [comment]
Can you check if the `\r\n` is gone? Have to check for the weird spaces another time.

**Comment by db-2001** [comment]
Is this in the cuttingedge branch? I'll check it when I get back from work.

**Comment by db-2001** [comment]
Yup, fixed
