### ISSUE TITLE
[It broke]: Incorrect AprilFoolsMode check?

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#178]
### What is broken?

POST /Settings/AprilFoolsMode?enabled=false returns 404 error, does there need to be !bool in the screenshot below?

### Additional stuff

![image](https://github.com/C9Glax/tranga/assets/125827669/6b6c295b-0081-4636-9804-d9312e3407f6)

**Comment by C9Glax** [comment]
Yup, that was a wrong check, however it should be a 400 error code not 404?

**Comment by db-2001** [comment]
It was 400 something, wasn't looking too closely tbh

**Comment by C9Glax** [comment]
Yea, just wondered if it might have been a separate issue 👍🏼
