### ISSUE TITLE
[It broke]: Chromium Browser Times Out Instantly

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#179]
### What is broken?

Starting the latest cuttingedge image, I notice that the chromium browser doesn't download and times out immediately. Normally I see a bunch of check jobs but that doesn't seem to be happening.

### Additional stuff

![image](https://github.com/C9Glax/tranga/assets/125827669/815868b4-8532-4bad-9fbc-396191f2d5e1)

**Comment by C9Glax** [comment]
the "30000ms" timeout means that is timeout value, not that it did. If it actually timed out, it would say so.
The checkjobs running on startup was an old issue, that was actually a bug, now you can see it will be 24 minutes before the next job is scheduled to run.

So nothing is actually broken :)

**Comment by db-2001** [comment]
Ah, gotcha, good to know we're cleaning up start up behavior

**Comment by C9Glax** [comment]
👍🏼 Somewhere the export of jobs to files got lost, so on startup all the jobs would run, as they were scheduled weeks ago
