### ISSUE TITLE
Modify download queue number

### ISSUE THREAD

**Issue by R3tr097** [C9Glax/tranga#18]
I was considering the thought of adding this possibility, like on torrent downloaders, to modify the queue size

**Comment by C9Glax** [comment]
Hey there!

Currently there is no "queue-size" as all publications/manga are being checked on set intervals and if during that regulat check a new chapter is found, it is added to the queue for that specific Connector (the scanlation site).
Rate-Limits prevent multiple simulataneous downloads from the same site, however different connectors will already download in parallel.

If you have a different feature in mind, please explain.

**Comment by R3tr097** [comment]
Ok, thanks for the fast response
