### ISSUE TITLE
Feature - Missing chapters?

### ISSUE THREAD

**Issue by lsultana98** [C9Glax/tranga#19]
Hey mate, great progress on this. Any chance we could have a feature outlining any potential missing chapters per manga? Doing a cross-check between the downloaded files and the original source?

**Comment by C9Glax** [comment]
You mean a feature that shows which Chapters from a specific source exist on disc?

**Comment by lsultana98** [comment]
Yes exactly, would be helpful for larger mangas (One Piece as an example)

**Comment by C9Glax** [comment]
Hmm,
I can certainly Implement something like that for Chapters that have been downloaded through tranga, it would be more difficult to do on other chapters, because I don't know their naming scheme.
I will bump this once it has been implemented.
