### ISSUE TITLE
Enhancement - Notifications for new downloads

### ISSUE THREAD

**Issue by lsultana98** [C9Glax/tranga#21]
I don't know the possibility of getting this done without doing hundreds at a time during initial bull download. Mainly just for new releases. 

I use Lunasea for my notifications with Sonarr/Radarr etc. Doesn't haven't to be this, just an example of a cool tool. 
https://docs.lunasea.app/lunasea/notifications/custom-notifications

**Comment by C9Glax** [comment]
Yes the idea of notifications was already brought up somewhere else, however using Gotify.
To avoid notification spam, I would only notify on completion of a monitoring task, with the new chapters.

**Comment by C9Glax** [comment]
Hello there,
I just finished adding support, however I couldn't test the lunasea implementation.

If you could do me a favor and test wether it works by adding your own webhook and then adding a new monitoring task, that would be greatly appreciated.

**Comment by lsultana98** [comment]
I am a little confused at what I am trying to do here 😂 sorry mate, if you could give me a lil more info

**Comment by C9Glax** [comment]
Okay so I guess you already pulled the updated containers.
In the settings on the webpage (top right corner) there should now be an option for the lunasea webhook.
I have just read the documentation again, and you can either use an existing webhook from the official modules (lidarr, etc.), or one of the custom webhook:
`https://notify.lunasea.app/v1/custom/device/:device_id`
`https://notify.lunasea.app/v1/custom/user/:user_id`
Replace `device_id` or `user_id` with your specific id.

When you set up sonarr it looked like [this](https://docs.lunasea.app/lunasea/notifications/sonarr), the url should include your user/device id.

**Comment by C9Glax** [comment]
Also please don't paste your specific ones here, they are unqiue to your device/user and secret.

**Comment by lsultana98** [comment]
I've done this now, just need to wait for a new release ahaha. Any chance you could add a test notification button?

**Comment by lsultana98** [comment]
Okay big issue, I believe changing this has broken the tranga-api functionality somehow. I will attach logs. 

[tranga.txt](https://github.com/C9Glax/tranga/files/11784155/tranga.txt)

**Comment by C9Glax** [comment]
Hmm yes, it seems that 1 or both of the following problems has occured:

1. I forgot to add a deserializer for the LunaSea-Object (fixed just now, will push release later)
2. Some formatting of the provided URL is not liked by the deserializer. (Not likely)

Will bump again when I have pushed the release. Should probably already fix the problem.

**Comment by lsultana98** [comment]
[trangalogs.txt](https://github.com/C9Glax/tranga/files/11797883/trangalogs.txt)

Same looking error, i have attached the logs post update.

**Comment by C9Glax** [comment]
[0f0902c93207ced7ab9cb0dfdef94e30454b7a4a
](https://github.com/C9Glax/tranga)
Okay because parsing the full url cause this issue I changed some things.
You now only enter the part: `device/:id` or `user/:id` on the website.
To fix your settings.json simply edit the value
```
"notificationManagers": [{
            "notificationManagerType": 1,
            "webhook": "someThingSomeThing"
        }
    ]
```
to simply `"notificationManagers": []`

**Comment by lsultana98** [comment]
Okay so that fixed that error, but now I have a new one where the web interface doesn't display what I've had in the past, or function at all. 
![webui](https://github.com/C9Glax/tranga/assets/45834283/99671449-34de-40dc-8319-f9f63ff4922c)
[tranga.txt](https://github.com/C9Glax/tranga/files/11827072/tranga.txt)

**Comment by C9Glax** [comment]
Hmm can you clear your cache (ctrl+f5 or shift+f5 one of those)? Could just be that the cached javascript files don't mix well ;)
If it still persists can you take a screenshot of the developer console -> network page?

**Comment by lsultana98** [comment]
I've tried multiple browsers and cleared cache and incognito, no luck.

**Comment by lsultana98** [comment]
![Screenshot_1](https://github.com/C9Glax/tranga/assets/45834283/7c8a6127-46c0-4cfe-a1bb-8198605b322c)

**Comment by C9Glax** [comment]
Okay one more easy solution:
Have you changed the port in docker-compose to 6531:6531 ?
Last release I finally got that working instead of 80.

**Comment by lsultana98** [comment]
That fixed that issue, now onto the notifications. I am not receiving the auto one after set up or docker start. 

Is the proper way: (this is a fake unique string)
/device/cjfsdjkhfsdjkhsjkhfsda0vEtat-m1S-LN-N3J4DFgxNRSECkk153_HkEkep5l8Qr9PvJGupsdfsdfsdfsdfM1Q0oZtN2pEGqQnT3c3b2W61_fONjWcNehQAZE-4D_esTymb8l4
or
cjfsdjkhfsdjkhsjkhfsda0vEtat-m1S-LN-N3J4DFgxNRSECkk153_HkEkep5l8Qr9PvJGupsdfsdfsdfsdfM1Q0oZtN2pEGqQnT3c3b2W61_fONjWcNehQAZE-4D_esTymb8l4

**Comment by C9Glax** [comment]
Glad that wasn't a real issue ':)
string should be `device/gfgzffg`

**Comment by lsultana98** [comment]
I am not having any luck here with this. Definitely the right ID as I have notifications for sonarr/radarr/tautulli already

**Comment by C9Glax** [comment]
Okay I will have to read over the documentation once again I guess.
I get a 200 success on any webhook (even the official lidarr and radarr ones) but no notifications as well...

**Comment by C9Glax** [comment]
Okay lunasea didnt like that i provided the image field, but didnt provide a valid url.
If you use it now `device/<id>` or `user/<id>` it should work. At least it did for me :)
