### ISSUE TITLE
[New Connector]: sushiscan.net

### ISSUE THREAD

**Issue by aski94140** [C9Glax/tranga#217]
### Website-Link

https://sushiscan.net

### Is the Website free to access?

- [X] The Website is freely accessible.

### Anything else?

Greetings from France ! 

Can you add this Connector  in french please ? 
Thanks a lot ! 

Your app is amazing

**Comment by C9Glax** [comment]
Duplicate of
https://github.com/C9Glax/tranga/issues/118
https://github.com/C9Glax/tranga/issues/129

The website is cloudflare protected, so 1) scraping it will be impossible, and 2) I myself have not been able to access it from Germany or the Netherlands on multiple machines.

So sorry, to say, no.
