### ISSUE TITLE
Add Option to Ignore Duplicate Chapters

### ISSUE THREAD

**Issue by Nas-77** [C9Glax/tranga#219]
Hi I was wondering if it would be possible to add an option (e.g. environment variable) we could set to ignore duplicate chapters that have already been downloaded? (e.g. Mangadex having multiple version of chapter X)

This is just a sample logic: 
Before proceeding to download a chapter, Tranga would scan the download folder of the manga/manhua for all existing files that would match the chapter number. If a match is found it would not proceed with the download.

**Comment by C9Glax** [comment]
I am not sure exactly what is missing.
Tranga is already not re-downloading chapters that exist (e.g. Volume and Chapter numbers matches).
Mangadex having multiple versions of the same chapter? Can you give an example (link or screenshot) 
If there is duplicates of the same chapter in Tranga let me know and reopen this please.

I'll add an Issue specifically for mapping chapters to files, as that has been on my mind as well 👍🏼

**Comment by Nas-77** [comment]
Rechecking the chapter list in MangaDex, I think this could have been a source problem assigning a volume to a chapter causing it to redownload since Tranga thinks it's a new chapter.

MangaDex link: https://mangadex.org/title/99daf7bc-3a3b-4fe8-b10d-951b32bfea64/gimai-seikatsu

Below is a screenshot of the chapters downloaded by Tranga. From there we could see a duplicate of Chapter 18.1 and 18.2, one with and one without a volume number. 

<img width="896" alt="Tranga Download" src="https://github.com/user-attachments/assets/d3ff23b0-719c-4229-9818-28d661659a83">

**Comment by Nas-77** [comment]
As for MangaDex having multiple version of the same chapter. 

Here is a link and screenshot of such manga:
https://mangadex.org/title/ade0306c-f4b6-4890-9edb-1ddf04df2039/solo-leveling-ragnarok
![image](https://github.com/user-attachments/assets/7773cee7-fcc7-4983-af8c-cea5483d02f1)


So far there are no duplicate chapters downloaded by Tranga. However, once MangaDex assigns a volume to the chapters, Tranga could possibly redownload them as seen in the previous comment.

**Comment by C9Glax** [comment]
I see, Tranga should actually just rename those existing chapters with the added volumes, and so far that seemed to have worked...
I'll keep an eye on it, but the space after the chapter number indicates a very old version of tranga...

**Comment by Nas-77** [comment]
I think those with the space after the chapter number were downloaded with the March master build. I have updated quite a few times since then (tried cuttingedge for a while then went back to master). 

Is it possible that the current Tranga version I have (April master build) doesn't have the feature you mentioned of renaming existing chapters? Or if it does, does it not have backwards compatibility with chapters downloaded using the old naming scheme?

**Comment by randrini** [comment]
Sorry to jump in but I my self got duplicate chapters from MangaDex as well;
![image](https://github.com/user-attachments/assets/0b451a18-931c-4dd2-910d-99db5344d9c7)
![image](https://github.com/user-attachments/assets/e843a7a0-ca8c-48a1-b1aa-87ebb65e178c)
I'm with the normal build.
How do I use the cuttingedge or v2 build with docker compose please ?
Thanks in advance

**Comment by C9Glax** [comment]
Okay I am wondering with the file sizes, and that for example 5-Monster and 6-Monster have different pagecounts and covers...
The chapter 1 and 2 having duplicates is due to there being external links
![image](https://github.com/user-attachments/assets/df7ff6fb-4352-42ff-a116-1fdf6ac78ca3)
which should have been fixed here 
https://github.com/C9Glax/tranga/commit/94582496ef181603bf8f42d52269fb6cc6365fac
and 5/6 is because it returns two results in English.
![image](https://github.com/user-attachments/assets/604652b1-a72e-4c18-8e12-c0328d7f565e)

Gonna look into that then 👍🏼

**Comment by randrini** [comment]
Thanks,
Btw is there a way to test that fix on a docker?

**Comment by C9Glax** [comment]
Got a fix on main machine, didn't push, next week 👍🏼

**Comment by C9Glax** [comment]
Fixed in `cuttingedge`

**Comment by bubez81** [comment]
Hello, think this is the right post.
Since yesterday Mangaworld is re-downloading all the chapters.
It seems like it's a name problem.
For example from "Return of the Mount Hua Sect - Vol.0 Ch.01" to "Return of the Mount Hua Sect - Vol.0 Ch.1" or from "Sugarless - Vol.01 Ch.01" to "Sugarless - Vol.1 Ch.1"

**Comment by C9Glax** [comment]
Yes changed the volume and chapter parsing to be actual numbers instead of strings, so it is messing with filenames. I am surprised it is not seeing that 01 and 1 are the same?

**Comment by bubez81** [comment]
yes, actually...
In the meantime, I delete the old files and keep the new ones.
