### ISSUE TITLE
[It broke]: User Agent field doesnt get saved permanently

### ISSUE THREAD

**Issue by ElryMoe** [C9Glax/tranga#226]
### What is broken?

This field in the Settings isnt saved when the container gets rebooted:
![image](https://github.com/user-attachments/assets/ab2cb4ba-a16f-402a-9265-1afbbb6467d2)

But the Requests fields seem to keep what i set them to:
![image](https://github.com/user-attachments/assets/c67e7d10-7f5c-48e5-9b53-7fd31fdb662f)

### Log-output

Nothing happens in logs when i save either of em.

**Comment by ElryMoe** [comment]
It just happend again when watchtower updated my tranga-api container to the latest cuttingedge

**Comment by C9Glax** [comment]
> I think you missed this one

Working on it still, can only code so fast :P

**Comment by ElryMoe** [comment]
Haha yeah im not expecting it to he already done, just since there was no response i thought you missed it ^^On 26 Aug 2024 12:09, Glax ***@***.***> wrote:

I think you missed this one

Working on it still, can only code so fast :P

**Comment by C9Glax** [comment]
Okay should be fixed.

**Comment by ElryMoe** [comment]
That was fast, thanks, will check it out as soon as im home

**Comment by ElryMoe** [comment]
Yep its fixed thanks
