### ISSUE TITLE
[It broke]: Server V2 Search Broken

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#239]
### What is broken?

Working slowly on the new front-end and was trying to tackle the search today, tried the new API call in API_Calls V2.md but got the following error: 
![image](https://github.com/user-attachments/assets/eb6004c6-1b27-40f6-b93e-928e2ed2eab0)

As a side note, is there no ability to search specifically by connector now? Don't have a preference either way necessarily, just need to know if I need to remove the drop down or not :)

**Comment by C9Glax** [comment]
> As a side note, is there no ability to search specifically by connector now?

There is [`/v2/Connector/<ConnectorName>/GetManga`](/v2/Connector/<ConnectorName>/GetManga)

Gonna look into the enumeration error

**Comment by db-2001** [comment]
May be related: 
![image](https://github.com/user-attachments/assets/d2e46c68-7ecd-4baa-a9fb-788ca280556b)

**Comment by C9Glax** [comment]
Should work now, the second screenshot you sent is a Connector Issue.
