### ISSUE TITLE
[It broke]: Performance problems on startup

### ISSUE THREAD

**Issue by ElryGH** [C9Glax/tranga#240]
### What is broken?

If you start the container with like 200 mangas you get a starting list of those hundreds to check.
This basically makes the entire machine unusable and goes on for atleast 1 hour, would it be possible to check the manga in the list in an interval and not all at once ?

### Additional stuff

![image](https://github.com/user-attachments/assets/fd346927-c340-4eb3-82b3-4b6b16b25de8)
![image](https://github.com/user-attachments/assets/ae80537b-ef24-4d40-99a4-0541b6bc8338)
![image](https://github.com/user-attachments/assets/5b9ad0a5-a638-45d0-8371-d2de65e497c8)

**Comment by C9Glax** [comment]
Don't @ me.
Will look when I have time.

**Comment by C9Glax** [comment]
Okay, I found an instance, where a page/tab would not be closed when it did not load correctly.
Also moved to a singular Chromium instance.
2dac5db4da6313bd2b6b225856c05e6c8a14f280
lmk if this fixes the issue
