### ISSUE TITLE
[It broke]: Not downloading fully

### ISSUE THREAD

**Issue by ElryGH** [C9Glax/tranga#242]
### What is broken?

Referencing: https://github.com/C9Glax/tranga/issues/241
It appears that its just not downloading some manga fully.
For AoT i see chapters till 92 & 108 nothing inbetween those and it should go to 139.5

**Comment by C9Glax** [comment]
Don't @ me, I don't work for you.
```
ChromiumDownl | Could not load Page:
One or more errors occurred. (Timeout of 10000 ms exceeded)
```
Nothing I can do, if the Browser is not loading the page.
