### ISSUE TITLE
V2: Readding deleted Manga without deleting folder crashes Tranga

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#243]
### What is broken?

Tranga V2 crashes when trying to re-add a removed manga without deleting it's folder first

![image](https://github.com/user-attachments/assets/0ac20e29-8278-420f-9dc7-5f76774548be)

**Comment by C9Glax** [comment]
Okay, since we don't want to delete existing contents of the "newfolder" we are gonna overwrite files that exist and add new ones, without deleting existing files.
