### ISSUE TITLE
[Docker] Mangasee and Manganato sources not giving any results

### ISSUE THREAD

**Issue by vodkapmp** [C9Glax/tranga#25]
When doing a search for a manga via the Mangasee or Manganato sources I get no results.
It looks like nothing at all happens, I click search and the UI seems to reflect no results by instantly going back to be ready to search again.
Using Mangadex works, it gives me results after a couple seconds.

In the logs all I see is "Getting Publications (title=<search term>)" and then nothing

I'm using the latest docker, everything setup just like in the docker-compose example

**Comment by vodkapmp** [comment]
Ok so I tested a bit more..
It seems to be that spaces break it, for example if I search "The Great Jahy Will Not Be Defeated" there are no results for either source. But if I just do "Jahy" I get the manga I want.

**Comment by C9Glax** [comment]
If you pull latest image it should work now :)
