### ISSUE TITLE
[It broke]: dupplicates again

### ISSUE THREAD

**Issue by BijuuKrunos** [C9Glax/tranga#251]
### What is broken?

After i fixed yesterday the problems i got and all mangas were finished downloading and up to day, in the night the pod restarted and now i have a lot of dupplicates again, even some which i deleted because of wrong download site (because i wasnt sure which i had before) are there again, it seems something is still broken here. Could it have something to do with the tranga-website because i am using the master branch here?

### Log-output

```C#
Nothing to show here.
```

**Comment by BijuuKrunos** [comment]
mhh after i restarted my second tranga-api deployment its broken too, all duplicates xD

**Comment by C9Glax** [comment]
https://github.com/C9Glax/tranga/issues/250#issuecomment-2358953494
I think this is it. Should be fixed with what is building now. Otherwise lmk.
