### ISSUE TITLE
Connector MangaKatana - Faulty Title Sanitation

### ISSUE THREAD

**Issue by ChrislyBear-GH** [C9Glax/tranga#255]
### What is broken?

The title sanitation of the MangaKatana connector is faulty. If you search for the manga "Oshi No Ko" (https://mangakatana.com/manga/oshi-no-ko.24487) the connector will query "https://mangakatana.com/?search=oshi_no_ko&search_by=book_name", which doesn't contain the desired manga.

If you instead search for "https://mangakatana.com/?search=oshi%20no%20ko&search_by=book_name", then the correct manga will be the first search result. 

Sanitizing the title by concatenating it with "_" is wrong. It should be "%20" or "+".
https://github.com/C9Glax/tranga/blob/8316ed08a78d87099ac3d5cf30fece8cf0e68925/Tranga/MangaConnectors/MangaKatana.cs#L18C1-L18C6 

Chris

**Comment by C9Glax** [comment]
Thanks for already doing all the investigative work! New `cuttingedge`-Image is building right now, and includes the `%20` fix!

**Comment by ChrislyBear-GH** [comment]
Thank you for the quick fix! Unfortunately, all I get niw after the update is

exec /usr/bin/dotnet: exec format error

I'm running  the API container on a Raspberry Pi with a arm64 architecture. I'm currently using the "latest" tag, because the "cuttingedge" tag gave me the same error.

It seems like something went wrong while building the image; this sound like the dotnet version of the arm64 image isn't compatible with the arm64 architecture.

Chris

**Comment by C9Glax** [comment]
Yeah... for some reason Github actions is just not building an ARM image at the moment? I'll look into it.

**Comment by ChrislyBear-GH** [comment]
That's weird. Thanks for answering so quickly!

I have now switched from using your prebuilt image to building it myself on the target system using
build: https://github.com/C9Glax/tranga.git#master
instead of
image: glax/tranga-api:latest

and it's working fine! With this workaround you can take your time fixing this :)

Thanks for this great application!

Chris

**Comment by C9Glax** [comment]
Yeah, still weird. The fix for this issue is still only on cuttingedge though... So probably should build that branch insted ;)

**Comment by C9Glax** [comment]
Oh I think I figured it out!
`--platform=$TARGETPLATFORM` instead of `$BUILDPLATFORM` works indeed better when building ARM...
