### ISSUE TITLE
Mangasee search not working

### ISSUE THREAD

**Issue by vodkapmp** [C9Glax/tranga#26]
When searching for something with Mangasee there seems to be an issue where it only searches the first word before a space.
When I search for "The Great Jahy" the search is just going and going, and looking at logs it is returning everything on Mangasee with "The" in the title.
![image](https://github.com/C9Glax/tranga/assets/70449815/c60504f4-b10c-490c-a52e-8566a1f827cf)

**Comment by C9Glax** [comment]
Problem is, that the search returns **all** results with any of the search terms in it.
So "The Great Jahy" will return all results including "the", "great", and "jahy". This is bad and there is a list that includes these bad terms ("the") - which previously didnt include "the".

Have a look at line 187 in Mangasee.cs:
`string[] badWords = { "a", "so", "as", "and", "the", "of", "that", "in", "is", "for" };`
If you can think of any more words that should be removed from search let me know.
