### ISSUE TITLE
[Feature Request] add Manga via URL instead of search

### ISSUE THREAD

**Issue by baal000** [C9Glax/tranga#264]
I found slight issues in the search which make it hard to add some mangas.
A possible solution for the issue that the search does not find the requested Manga (even though it is available on the site) would be to add the possibility to put in the URL to the manga on a supported source and it add to the lib in that way. 

Or ,if that is not possible in the WebUI, at least add an API Endpoint with which we can do that.

**Comment by C9Glax** [comment]
Already works exactly as you said.
Copy the URL, select the connector on the site, paste and hit enter.
