### ISSUE TITLE
MangaKatana - When search returns single item no list is returned.

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga#27]
When searching for a Manga that returns a single result (in my example `I Wanna Quit Being a Hitman!` or just `i wanna quit`), the connector doesn't work, because you are getting automatically redirected to the only result.
![grafik](https://github.com/C9Glax/tranga/assets/13404778/8454e761-dbdd-4d51-bf3b-1eedc3ecb69d)
@arxae if you want to maintain this let me know, otherwise I will do it.

**Comment by arxae** [comment]
Should be pretty easy to bypass the search scrape. I'll get it done, no eta on it though

**Comment by C9Glax** [comment]
Thanks, take your time :)
