### ISSUE TITLE
[It broke]: MangaDex not downloading all chapters and names the files wrong, if chapter number is reoccurring in volumes

### ISSUE THREAD

**Issue by absturztau-be** [C9Glax/tranga#271]
### What is broken?

Found out that tranga doesn't download all chapters from mangadex and missnames chapters, if the manga has another volume with restarting chapter numbers (for example vol11 in [Happy Sugar Life](https://mangadex.org/title/010a8606-ab4f-4e3e-82ce-17f19b02f262/happy-sugar-life))

in case of happy sugar life, it looks like tranga has downloaded vol1 ch1 but renamed it to vol11 ch1. all actual chapters from vol11 are not downloaded

no logs, since they seem to be irrelevant to this bug

### Additional stuff

running on latest tag

**Comment by C9Glax** [comment]
Think I found the issue.
Gotta take a moment to think about how to solve both problems...
https://github.com/C9Glax/tranga/commit/ec8eb4094136466ff9c5908dfc3ec0247fc9fe62
Knew there was a reason why I checked both .- .

**Comment by C9Glax** [comment]
The issue being that Mangadex itself sometimes assigns volume-numbers, then removes them, triggering a re-download, and causing duplicate chapters...

**Comment by absturztau-be** [comment]
i see, that indeed is troublesome.

i don't mind, if it misses some downloads because of this, because i think this is quite a niche case (the double chapter numbers, i mean), but at least tranga should rename the chapters to its first occurrence instead to the last so it matches to what is actually downloaded

**Comment by C9Glax** [comment]
Okay I think I found a way to preserve both. But I don't know how it will handle Filename collisions atm...
