### ISSUE TITLE
[New Connector]: weebcentral

### ISSUE THREAD

**Issue by Hail28** [C9Glax/tranga#278]
### Website-Link

https://weebcentral.com/

### Is the Website free to access?

- [X] The Website is freely accessible.

### Anything else?

The Owners of Mangasee123 & Manga4life said that this will be their primary site now, will this site be added to the available search options? Thanks

**Comment by C9Glax** [comment]
Looks good, whenever I get the time 👍🏼

**Comment by Hail28** [comment]
Okay Thanks 😘

**Comment by ale-ben** [comment]
Started working on this here https://github.com/ale-ben/tranga/tree/feature/weebcentral.
I'll see how far I can get

**Comment by C9Glax** [comment]
Very cool 😎 
Can you make a PR Draft?

**Comment by ale-ben** [comment]
> Very cool 😎 Can you make a PR Draft?

Created.
On which branch should I merge?  I'm working on master right now but I can swap

**Comment by C9Glax** [comment]
`cuttingedge` would be best, since that also gives time to test before breaking master.

**Comment by ale-ben** [comment]
Ok, code should be working.
Tomorrow I'll clean the code a bit and test it with website. It's been a while since I worked at something till 1 AM!

Switched the PR branch to `cuttingedge` as requested
