### ISSUE TITLE
[It broke]: No search bar?

### ISSUE THREAD

**Issue by IsXGeo** [C9Glax/tranga#286]
### What is broken?

Using latest, I would expect for there be a search bar to put my query into

Fresh install, tried both windows and linux, podman and docker. Same results.

Also tried cuttingedge, but that just says the api url doesn't work.

### Log-output

```C#
[11/30/2024 09:25:55.642]        Logger | Logfile: /usr/share/tranga-api/logs/11/30/2024_9-25-55.log
[11/30/2024 09:25:55.798]        Tranga |

 _______
|_     _|.----..---.-..-----..-----..---.-.
  |   |  |   _||  _  ||     ||  _  ||  _  |
  |___|  |__|  |___._||__|__||___  ||___._|
                             |_____|


[11/30/2024 09:25:55.847]       JobBoss | Next job in
[11/30/2024 09:25:55.871]        Tranga | {
  "downloadLocation": "/Manga",
  "workingDirectory": "/usr/share/tranga-api",
  "apiPortNumber": 6531,
  "userAgent": "Tranga (Unix; x64) / 1.0",
  "aprilFoolsMode": true,
  "version": 2,
  "requestLimits": {
    "MangaInfo": 250,
    "MangaDexFeed": 250,
    "MangaDexImage": 40,
    "MangaImage": 60,
    "MangaCover": 250,
    "Default": 60
  },
  "bufferLibraryUpdates": false,
  "bufferNotifications": false
}
[11/30/2024 09:25:55.878]        Server | Listening on http://*:6531/
```

### Additional stuff

![image](https://github.com/user-attachments/assets/04d5ca9d-1cb5-4e12-b260-f894e790b50b)

**Comment by C9Glax** [comment]
Can you look at your Developer View and check if the textbox is there?
![image](https://github.com/user-attachments/assets/d7523ee2-652f-4639-80d2-ff6a63b57444)
ID is `#newMangaTitle`

Because I can't reproduce and it is a static site, so there is no reason why it shouldn't be there.

**Comment by IsXGeo** [comment]
Yeah It ended up being my browser, with I thought I had tried another but apparently not.

![image](https://github.com/user-attachments/assets/5745f829-f25f-4f13-bb8f-e3be677da830)\

I'm using Arc which even though uses chromium, just chooses to ignore that text field element. :/
