### ISSUE TITLE
[It broke]: Unable to add new manga

### ISSUE THREAD

**Issue by Hooteo** [C9Glax/tranga#288]
### What is broken?

I'm not able to search for new manga:
![image](https://github.com/user-attachments/assets/15c02add-e210-4a1c-a667-cee104de91f5)

My config:
  tranga-api:
    image: glax/tranga-api:latest
    container_name: tranga-api
    volumes:
      -  /mnt/leonardo/manga:/Manga
      -  /opt/cont/tranga:/usr/share/tranga-api
    ports:
      - "6531:6531"
    restart: unless-stopped
  tranga-website:
    image: glax/tranga-website:latest
    container_name: tranga-website
    ports:
      - "9555:80"
    depends_on: 
      - tranga-api
    restart: unless-stopped

It seems like the search function is not working, the app is downloading correctly the already added manga.
I tried with Mozilla, Chrome, Edge and Brave browser.

### Log-output

```C#
There are no new logs when trying to search.
```

**Comment by C9Glax** [comment]
Duplicate
https://github.com/C9Glax/tranga/issues/286
