### ISSUE TITLE
[Feature] Exposing only one port

### ISSUE THREAD

**Issue by shyim** [C9Glax/tranga#301]
Hey,

to simplify hosting, it would be nice if I could just expose one port. Right now the web ui directly speaks to api. If it just request himself and that forwards to the api would make it easier or merge website and api into one container

**Comment by 92061** [comment]
No. Dont host this accessible publicly. There is no authentication, nothing.
Also not the idea of this.

**Comment by C9Glax** [comment]
No it wouldn't, and  no dont expose this publicly. There is no authentication, everything is plaintext.
Also not the idea.

**Comment by shyim** [comment]
I think, you don't got what i tried to say. I want to use Tranga, but only expose one ports. 

I deployed api and website and the website directly talked in browser with the api.

**Comment by C9Glax** [comment]
No I got that, there is no reason to do it though, no benefit.
