### ISSUE TITLE
[Feature Suggestion] Add manga from compatible sources via link

### ISSUE THREAD

**Issue by vodkapmp** [C9Glax/tranga#32]
It would be a nice feature if one could add a manga with a link one has on hand, instead of needing to search for it in tranga.

I often browse mangasee, and find some new manga I want to read. 
Being able to just copy the link and paste it into tranga to add it would be neat.

**Comment by C9Glax** [comment]
Should be a quick afternoon project, however I am probably not going to work on this for the next two weeks.

**Comment by C9Glax** [comment]
@vodkapmp Will be in the new release! (see above)
