### ISSUE TITLE
apiUri is not saved from the website

### ISSUE THREAD

**Issue by schklom** [C9Glax/tranga#36]
The apiUri setting does not get saved from the Settings on the webpage.
I run the website and API Docker containers.

A dirty hack is to set a cookie `apiUri` manually

>Bigger problem is that the website has hardcoded fetches to port 6531...
>
>You need to also expose tranga-api on reverse proxy, and manually via browser's dev tools set a cookie "apiUri" that points to it.
>It should work after a reload.

_Originally posted by @kacpak in https://github.com/C9Glax/tranga/issues/35#issuecomment-1645654943_

but this is not great.

Ideally, it can be set in `settings.json` along with the other settings.

**Comment by C9Glax** [comment]
`settings.json` is for tranga-api only.

> A dirty hack is to set a cookie apiUri manually

> You need to also expose tranga-api on reverse proxy, and manually via browser's dev tools set a cookie "apiUri" that points to it.

The cookie `apiUri` is set on the website (settings > API-URI), only for the website. Press Enter to confirm and maybe reload...
If you have a setting that cleares cookies, then you have to set it every time, or make an exception.

**Comment by schklom** [comment]
> Press Enter to confirm

I was pressing the `Update` button. With Enter, it works x)

**Comment by schklom** [comment]
@kacpak You need to press Enter to save the API-URI, not the Update button :P

**Comment by kacpak** [comment]
I did, at the time it didn't want to work 🤷 
I'll check again when I'll come back to the topic, for now I pasued manga automation on my homelab :)
