### ISSUE TITLE
Settings are not loaded from settings.json

### ISSUE THREAD

**Issue by schklom** [C9Glax/tranga#37]
1. Set URLs and passwords in the Settings
2. Open the website on another device e.g. phone
3. The website is blank: no settings, no mangas.

Is it possible to load the information from `settings.json`?

**Comment by C9Glax** [comment]
no. settings.json is only for tranga-api. 
Website is a client-side page, that stores everything on the individual machine.

**Comment by C9Glax** [comment]
> The website is blank: no settings,

The settings are saved and loaded in tranga-api. If you provide the correct API-URI on the website, they can actually be loaded.

**Comment by schklom** [comment]
> If you provide the correct API-URI on the website, they can actually be loaded.

Oh, it's okay then. Thanks!
