### ISSUE TITLE
Website: Settings Update does not save API-URI

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga#38]
#36

**Comment by ElryWeeb** [comment]
whats completed on this ? Its still not saving, the thing you entered just dissapears

**Comment by C9Glax** [comment]
If you look at the commit you can see it is fixed.
https://github.com/C9Glax/tranga/commit/98ec0b837fc77417c24603cd4be0f87303eeaaf4
If you look at this video it is fixed.

https://github.com/C9Glax/tranga/assets/13404778/bdbfd04b-0ec6-4a2c-8745-deceefc86b91

**Comment by ElryWeeb** [comment]
> If you look at the commit you can see it is fixed. [98ec0b8](https://github.com/C9Glax/tranga/commit/98ec0b837fc77417c24603cd4be0f87303eeaaf4) If you look at this video it is fixed.
> 
>  2024-01-20.16-20-58.mp4

yeah it was prolly the way i was accessing tranga-website, i will try it out with firfox on the vps trough a xrdp session
