### ISSUE TITLE
Can't rebind external/host port for tranga-api service in docker-compose

### ISSUE THREAD

**Issue by Takanashi-Yuri** [C9Glax/tranga#44]
I can't rebind external/host port for tranga-api in docker-compose.yml from "6531:6531" to for example "4006:6531". I think it has something to do with the tranga-website service using browser connected ip and hard-coded port "6531" in [Website/apiConnector.js](https://github.com/C9Glax/tranga/blame/a4f67c9ab4bbb3036d40fa51f530869e85532401/Website/apiConnector.js#L1) to connect to tranga-api.

You could make the port variable and let it be set in tranga/settings.json file that is already used for download location and working directory settings. Or make usage of docker networks and connect to the tranga-api through internal ports and service names.

**Comment by C9Glax** [comment]
Use [the settings](https://github.com/C9Glax/tranga/blob/master/screenshots/settings.png) and point API-URL to port 4000

**Comment by C9Glax** [comment]
settings.json is tranga-api only
