### ISSUE TITLE
not connect to kavita

### ISSUE THREAD

**Issue by Nikibasso94** [C9Glax/tranga#56]
not connect to kavita

i write the url http://192.168.0.79:5001 and user , pwd
![image](https://github.com/C9Glax/tranga/assets/112549678/8ef3ecc3-d57b-430f-a837-eb74fb9cd32a)

press enter or update
but the field turn empty

![image](https://github.com/C9Glax/tranga/assets/112549678/380d89dd-3c1f-4fad-8eb5-eac263d3a33e)

**Comment by C9Glax** [comment]
Same situation as #36 probably. Can you press the update button?

**Comment by Nikibasso94** [comment]
not work

**Comment by C9Glax** [comment]
Hmm, okay wontfix on the latest branch.
I just completed #41 
Check the README first, then update with the new docker-compose.yaml.
