### ISSUE TITLE
Losing catalog when updating image

### ISSUE THREAD

**Issue by Hooteo** [C9Glax/tranga#61]
### What is broken?

In my stack i'm using Watchtower to automatically update the docker images. I've lost all the manga catalog from Tranga, it's possibile to have the catalog in a persistent volume?

Thanks

**Comment by Hooteo** [comment]
Sorry, i notice that you can do it by setting the volume like that:
    volumes:
      - /dati/kavita/manga:/Manga
      **- /opt/cont/tranga:/usr/share/tranga-api**

**Comment by C9Glax** [comment]
Not just solely directed at you, but anyone else stumbling over this:
I recommend taking insipiration from the [docker-compose.yaml](https://github.com/C9Glax/tranga/blob/master/docker-compose.yaml), since the standard settings should work for most people.
