### ISSUE TITLE
Incorrect chapter numbering / Chapters in parts.

### ISSUE THREAD

**Issue by JohnnyBigoud** [C9Glax/tranga#63]
### What is broken?

Hello,

I am monitoring One-punch man through Mangasee.

- Chapters 1 and 2 downloaded are in fact chapter 132 part 2 (downloaded as chapter 1) and chapter 132 part 3 (downloaded as chapter 2).
- Of course chapter 132 is only containing part 1 of this chapter.

![image](https://github.com/C9Glax/tranga/assets/20937336/b4019df1-5f91-48f6-b9fa-040deb2ac5ce)

![image](https://github.com/C9Glax/tranga/assets/20937336/e8068681-6745-43cd-8b56-590a7aa714bd)

I guess some parsing of results name is involved?

**Comment by C9Glax** [comment]
Pushed the fix to cuttingedge.

**Comment by JohnnyBigoud** [comment]
Updating container empties the watchlist again.

I will delete downloads to check if the initial problem is solved.

**Comment by C9Glax** [comment]
> Updating container empties the watchlist again.

Can you open a new issue for this?
