### ISSUE TITLE
Pulling cuttingedge version is emptying tasklist

### ISSUE THREAD

**Issue by JohnnyBigoud** [C9Glax/tranga#65]
### What is broken?

My latest update totally emptied my tasklist.

Anything I can do to help the analisys?

**Comment by JohnnyBigoud** [comment]
Nevermind my docker-compose didn't keep the changes setting the folder to lower case for whatever reason. Updated the docker compose seems to have solved the issue.

The version to use is latest right? No more using cuttingedge?

**Comment by C9Glax** [comment]
@JohnnyBigoud Correct latest is now the active branch, development happens on cuttingedge, so if you have a bug and I push changes, they will be on cuttingedge first.
