### ISSUE TITLE
[Feature Request] Add Support for Ntfy for Notifications

### ISSUE THREAD

**Issue by hash004** [C9Glax/tranga#73]
### Is your feature request related to a problem? Please describe.
While Tranga currently supports Gotify for notifications, it would be beneficial for users who rely on Ntfy for their notification needs.

### Describe the solution you'd like
I would love to see support added for [Ntfy](https://github.com/dschep/ntfy) as a notification method in Tranga. This would allow users to receive notifications through their preferred platform, offering more flexibility and broadening the range of supported notification methods.

**Comment by C9Glax** [comment]
From a quick glance:
Ntfy is CLI based. There is no way to use the endpoint other than running a command.
Ntfy uses other backends to send notifications to.

**Comment by hash004** [comment]
You can send notifications via HTTP too and since the topic name is password enough there is no auth required. https://docs.ntfy.sh/publish/

The way I would imagine this being implemented is having 2 fields, hostname and topic, on the config page. And the POST request would use those details and body would contain the notification details.

**Comment by C9Glax** [comment]
I really didn't take a close look...
Then that's definitely easily achievable.
Thanks for pointing that out.

**Comment by C9Glax** [comment]
Hey there, I tried to blind-implement this. Don't know how well this will work as I don't have a server set up. `cuttingedge` should have both the website and api implemented.

**Comment by hash004** [comment]
Hey @C9Glax,
So I tried testing using `cuttingedge` image for the api and website but couldn't see any requests being sent when I looked at the api container:

![image](https://github.com/C9Glax/tranga/assets/2758955/81948035-a98c-4408-a067-952a4df4a52d)
![image](https://github.com/C9Glax/tranga/assets/2758955/63c1e23f-3db5-46e5-9ec7-502bf6d7093b)

I tried doing a postman request to see what it would look like and got it working with following setup:
![image](https://github.com/C9Glax/tranga/assets/2758955/938fbc11-54ad-4615-906a-b36e8ccd1cb9)

You can use the ntfy's demo server to play around if you want: https://ntfy.sh/tranga

**Comment by C9Glax** [comment]
Looking at the first picture tells me that the javascript in your browser is still cached, otherwise the Ntfyconfigured would either have a checkmark or an X.
Adding works on my side, just haven't seen if it actually sends notifications.

**Comment by hash004** [comment]
> Looking at the first picture tells me that the javascript in your browser is still cached, otherwise the Ntfyconfigured would either have a checkmark or an X. Adding works on my side, just haven't seen if it actually sends notifications.

You're right, my bad. Cleared my cache and only had the checkmark. Downloaded a chapter and got the following notification:
![image](https://github.com/C9Glax/tranga/assets/2758955/655ee065-aa6c-4732-a679-42771846aa24)

![image](https://github.com/C9Glax/tranga/assets/2758955/9f1c0ec2-36b6-44e6-b1fd-6cfafe97edd0)

Looks good to me with the quick testing I did 😊

Thank you for implementing it.
