### ISSUE TITLE
[It broke]: "A Returner's Magic Should be Special" does not show search results in MangaSee but adding from URL works

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#75]
### What is broken?

I searched for "A Returner's magic should be special" from MangaSee and it didn't return any search results. Putting in the link directly from mangasee123 works as expected. 

Link for testing: https://mangasee123.com/manga/A-Returners-Magic-Should-Be-Special

### Log-output

```C#
[10/30/2023 03:22:08.22 ]      Mangasee | No results.

[10/30/2023 03:22:08.22 ]      Mangasee | Retrieved 0 publications. Term="A Returners Magic Should be Special
```

**Comment by db-2001** [comment]
Ok, this seems to be an issue when you search things with spaces on MangaSee, searching just "Returners" brings up the right results. Behavior also noted with Komi Can't Communicate where searching "Komi" would bring up the search results but "Komi Can't Communicate" would bring up none.

**Comment by C9Glax** [comment]
I am using the websites search function, and this has already had it's fair share of issues...
Like a need to use dashes or similar shenanigans... I guess I need to revert that change, that made me switch from my own search function (that returned way too many results)...

**Comment by C9Glax** [comment]
Okay I reimplmented my own searchfunction, because as I said, the website is botched.
However right now it returns way too many results, and the naive recursive Levenshtein Distance implementation I tried just takes up way too many resources. (and time)

**Comment by C9Glax** [comment]
![grafik](https://github.com/C9Glax/tranga/assets/13404778/857f633a-a3b8-40f7-b46f-cd9d63128cbb)
