### ISSUE TITLE
[Enhancement] Return publication status of manga

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#77]
Add field in manga to return if publication is:

Ongoing
On Hiatus
Ended
Status Unavailable

**Comment by db-2001** [comment]
Ah my bad, unless I'm interpreting it incorrectly, there currently isn't an on hiatus status is there?

**Comment by C9Glax** [comment]
There is whatever status the website reports in there.
Every website does it a bit differently, but most have "ongoing", "ended", etc. I just copy the string.

**Comment by db-2001** [comment]
Ok, that makes sense, I can pull on haitus out on the website side. I was also hoping to separate cancelled and completed if possible and makes sense to you. Don't know if the API should be updated for that or if the API should just report whatever the connector status is and then I interpret it on the website side as needed.

**Comment by C9Glax** [comment]
It would make sense to have it unified on the api-side...
Can you make a list of sensible statusses? I will assign them appropriately for each website then...

**Comment by db-2001** [comment]
Yeah, thanks for taking care of this:

Continuing
On Hiatus
Completed 
Cancelled 

I doubt it will ever be needed but "Unreleased" is also a status I've seen on upcoming works.

**Comment by db-2001** [comment]
If you can let me know what you'll name the status' on the API side, I'll start a branch for the website side development.

**Comment by C9Glax** [comment]
Exactly that:
```
Continuing
On Hiatus
Completed
Cancelled
Unreleased
```

**Comment by db-2001** [comment]
When I pull the cuttingedge image the releaseStatus field isn't there, how can I clear the cache?

**Comment by C9Glax** [comment]
@db-2001 okay I don't know what's going on with your images. I just pulled cuttingedge api and website, and both seem to work for me?

**Comment by db-2001** [comment]
Hm okay, I've pulled down the images, pruned everything and then pulled and built them again and it was the same for me so I'll have to do some more tinkering on my side then to see what's going on

**Comment by C9Glax** [comment]
The website being broken could really just be cached files.
You can check if files are requested by running `docker logs tranga-website -f` and looking if the .css and .js files are being fetched.

**Comment by db-2001** [comment]
Yup, cached files were the issue -_-
