### ISSUE TITLE
[It broke]: Parsing of Manga Names with Special Characters

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#85]
### What is broken?

Manga Titles with special characters "+", "é" get left out when saving to disk. Example is The Café Terrace and it's Goddesses. This also causes issues when there is a manga called Citrus and then another called Citrus+, it saves the original as 'Citrus' and Citrus+ as 'Citrus ' and causes Kavita to confound the two.

### Log-output

```C#
N/A
```

**Comment by C9Glax** [comment]
The problem with these, is that special characters and directory names don't mix well.
I added a Regex that I know works with directory-names, + should work too, so I added that.
