### ISSUE TITLE
[It broke]: komga scan

### ISSUE THREAD

**Issue by C9Glax** [C9Glax/tranga#89]
### What is broken?

Deleted the old issue, because you can still see the url in history.

Hello,

I'm having trouble to properly configure the interaction with komga
My aim is to have the following behavior:

    the tranga download directory is a separate folder
    the komga library (currently one library) has its own folder
    My assumption is that by configuring komga in tranga settings, it will scan my library to avoid downloading Komga existing chapters

To this effect, I added komga in the parameters
The connection is valid
The scan result is valid (see logs)
However it doesn't take into account my library when downloading chapters, as it will try to redownload the whole serie.

Is it something that I didn' do properly or simply I'm expecting a non intended behavior?

edit : anonymising komga url

Cheers.

### Log-output

```C#
[12/03/2023 17:50:15.387]         Komga | Getting Libraries
[12/03/2023 17:50:33.871]     NetClient | GET https://XXXXXXXXX/api/v1/libraries -> 200: 
[12/03/2023 17:50:42.694]     NetClient | POST https://XXXXXXXXX/api/v1/libraries/0BWZMT2B7C06G/scan -> 202: 
[12/03/2023 17:50:59.335]         Komga | Updating libraries.
```

**Comment by C9Glax** [comment]
The intended behaviour is that Tranga downloads to a folder that is accessible by Komga, and is included in a Komga-Library.
The Komga-Connection is only used to trigger a scan of all libraries, check for duplicates is done on the folder.

**Comment by C9Glax** [comment]
stale

**Comment by Charles-Em** [comment]
Thanks for your reply.

Just to make sure I understand properly.
1 / I have to configure tranga to have its download folder be in a Komga library
2/ Is tranga going to scan all komga libraries ? (That's what I as hoping for) Or only the download folder ?

**Comment by C9Glax** [comment]
1. Komga needs access to the files tranga downloads, therefor the download directory of tranga needs to be a library in komga.
2. Tranga scans only its own download directory. If a filename is changed, it will mark the chapter to be downloaded again.
The problem with scanning for things outside of tranga is fuzzy-search being a whole world of itself, and false positives being a pain to handle.

**Comment by Charles-Em** [comment]
Thanks again
I think I understand my misconception now
Adding komga login credentials in tranga is to give tranga the rights to read/write in an external folder in case the underneath user wouldn't have the rights?

I will reorganize everything to match this.

**Comment by C9Glax** [comment]
komga login credentials in tranga are to send api requests to request a folder scan.
Tranga isn't as fancy as you think :P

**Comment by Charles-Em** [comment]
Makes sense, forgot about gaining acess to komga API

It may not be fancy, but it's damn cool :)
