### ISSUE TITLE
[It broke]: Created duplicate directories for Manga with different names

### ISSUE THREAD

**Issue by db-2001** [C9Glax/tranga#90]
### What is broken?

When downloading "I Want to Annoy the Cute Boss" from Mangadex, Tranga created two directories, one with the English title and one with the original Japanese title. Duplicate files are confirmed, this is not Kavita being weird with interpreting metadata.

**Comment by C9Glax** [comment]
I think the problem is that Mangadex changes the title/metadata very often. I haven't worked on Tranga in a minute, but this metadata-update is probably changing the directory tranga uses to check wether chapters exist.

**Comment by C9Glax** [comment]
@db-2001 do you know if this still happens? I remember that this was an issue i fixed relatively quickly see #81

**Comment by db-2001** [comment]
Yeah it still happens, specifically with the same manga

**Comment by C9Glax** [comment]
I think I found the issue... Can you pull `cuttingedge` and try again?

**Comment by db-2001** [comment]
Sorry for the late reply, in the process of moving so I haven't had time until now to set everything back up. I pulled the latest image and tried to start Tranga but was running into #108. I will say that after a bit it started working... randomly... but unless you think otherwise, I'm going to leave the issue up just so we have traceability that the issue did exist. I will get back to you about this issue once I can test it.

**Comment by C9Glax** [comment]
> going to leave the issue up just so we have traceability

yup!

**Comment by db-2001** [comment]
Issue seems resolved on my end.

**Comment by db-2001** [comment]
JK, it did it again :( , but with My Dress Up Darling, Damedol, and Nagatoro this time too (all Mangadex sources). Not sure if it's because I started the server in a long time and it forced a metadata update for everything which caused it.

**Comment by db-2001** [comment]
Haven't noticed this in a while
