### ISSUE TITLE
[It broke]: 400 Bad Request on getting manga

### ISSUE THREAD

**Issue by m8dotpie** [C9Glax/tranga#95]
### What is broken?

Since the website does not have a feature of fetching the chapters starting from one particular, instead of fetching all of them, I tried to directly tell API to do so, since there is a call `Jobs/DownloadNewChapters`, which allows this functionality.

1. I fetch the manga metadata from the `GET Manga/FromConnector` endpoint.
2. Use the `internalId` received in the following request
3. Neither `GET Manga/Cover`, nor `POST Jobs/DownloadNewChapters` don't work. 400 on both.
4. Expected to get job done, but did not

Is there anything I misunderstand with the API?

### Additional stuff

Logs don't have anything extraordinary, simply fetches the covers on `GET` and keeps silence, as expected, on `400 Bad Request`

**Comment by db-2001** [comment]
Since I'm on mobile I'm gonna have a thought time pulling it up but in the API when you initially add a manga to monitor, there is a field which let's you specify how many chapters you want to ignore I think it's ignoreChaptersBelow or something like that so if that number is 10 then it'll start downloading from 11. Caveat being because the tranga-webaite front end hasn't been updated for that yet, you would have to make that API call manually.

**Comment by C9Glax** [comment]
At some point in the far future I will write an API documentation for now:

1. `POST Jobs/DownloadNewChapters` will only start a configured job
2. `GET Manga/Cover` needs the internalId too, and a "cachedPublication" entry which I don't know rn if that exists if there isn't a configured job.

What you want is after fetching the `internalId`:
`POST Jobs/MonitorManga` [here](https://github.com/C9Glax/tranga/blob/cc8453d4a88af01479df80751c1483c8b8a2e37e/Tranga/Server.cs#L247) with `internalId`, `connector`, `interval `and the optional `ignoreBelowChapterNum`, there's also `customFolderName`.

**Comment by m8dotpie** [comment]
> 2\. `GET Manga/Cover` needs the internalId too, and a "cachedPublication" entry which I don't know rn if that exists if there isn't a configured job.

I have supplied the internalId to Manga/Cover, so I think there is probably no cached entry without job.

**Comment by C9Glax** [comment]
Stale
