### ISSUE TITLE
[Manga4Life]: access to all chapters

### ISSUE THREAD

**Issue by Charles-Em** [C9Glax/tranga#96]
### What is broken?

When using Manga4Life as a source, it will only parse the first chapter and the last 10 chapters

I think it is related to how this site presents its data since when using it manually, all other chapters are behind a "Show all Chapters" button press.

**Comment by C9Glax** [comment]
You are exactly right, trying to see if I can emulate a click now...

**Comment by C9Glax** [comment]
Okay it should be working now :)

**Comment by Charles-Em** [comment]
Thank you !

I forced update my docker, It does have a new date on last change (2024/01/03), but there is no change in behavior.

Any idea ?

**Comment by Charles-Em** [comment]
Ok so, I scrapped my containers and redid a clean install, I noticed that even if I was insiting on using the latest version of the image pulled, it was rebuilding with the previous image

Manga4life is now able to grab all chapters
But MangaKatana just died in the process x)

Will open a new issue with a log for mangakatana
