### ISSUE TITLE
[It broke]: Chapter naming for different seasons

### ISSUE THREAD

**Issue by Charles-Em** [C9Glax/tranga#97]
### What is broken?

On Mangasee/MangaLife, for Tower of God, the season of the chapter is not reflected in Tranga

The related problem is that every chapter number that is present in each season is named the same.

For exemple : 
S1 - Chapter 13
S2 - Chapter 13
S3 - Chapter 13
Are all renamed to "Tower of God - Vol.1 Ch.13"

On the websites, they use the word index to differentiate season 2 and 3 and nothing for season s1 in the URL, and S1 S2 S3 in the overlay : 
[S3 - Chapter 13](https://manga4life.com/read-online/Tower-Of-God-chapter-13-index-3-page-1.html)
[S2 - Chapter 13](https://manga4life.com/read-online/Tower-Of-God-chapter-13-index-2-page-1.html)
[S1 - Chapter 13](https://manga4life.com/read-online/Tower-Of-God-chapter-13-page-1.html)

https://manga4life.com/read-online/Tower-Of-God-chapter-13-index-3-page-1.html
https://manga4life.com/read-online/Tower-Of-God-chapter-13-index-2-page-1.html
https://manga4life.com/read-online/Tower-Of-God-chapter-13-page-1.html

Edit : I checked an other webtoon with seasons, and it is the same problem, with the same naming convention (presence of the word index in the url for seasons beginning from season 2, and S1/S2/etc in the overlay)

**Comment by Charles-Em** [comment]
Hello,

just tried this update, currently it's only downloading season 2+ chapters and labelled them as volume 1 (manga4life)
It's ignoring season 1 chapters (those without the word index)

**Comment by C9Glax** [comment]
@Charles-Em yea wrong comparison... works now

**Comment by Charles-Em** [comment]
Will retry soon, was doing a lot of upgrades here and there of my Nas setup (finally got some time to organize it)

**Comment by Charles-Em** [comment]
Ok, I feel like webtoons are going to be a pain x)

I tried on this one :
https://manga4life.com/manga/The-Gamer

It did pull 1 chapter of each number and all were labeled volume 1.
The sorting was like this : it took the highest season available for each chapter number.

Meaning it detected 154 total chapters, with 154 being the number of the highest chapter in a season (season 4 - Chapter 154)
And also "The Gamer - Vol.1 Ch.1 " was (https://manga4life.com/read-online/The-Gamer-chapter-1-index-7-page-1.html)
Season 7 being the last one with a chapter 1

**Comment by C9Glax** [comment]
Okay I just tried adding the Manga. Also 154 chapters shown. However in tranga itself it shows all 400-something chapters.

Problem was that there was a seperate check if a job already exists with the manga, that didn't work correctly. Should be fixed now.
